spring:
  datasource:
    driverClass: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/picea?characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: c9ReTv4T96SGcVe

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis-plus:
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jxrory.*.entity
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.jxrory.picea.**.enums

auth:
  bearer:
    version: "1" # bearer 版本号
    issuer: "picea" # "iss" (Issuer: 发行人)
    subject: "piceaJWT" # "sub" (Subject: 主题)
    duration: 10080 # bearer 的有限时间
    secret-key: "Fle#ien,Jjekx@KPm#nekix"